# Nessie Deployment & Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nessie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nessie
  template:
    metadata:
      labels:
        app: nessie
    spec:
      containers:
        - name: nessie
          image: projectnessie/nessie:latest
          ports:
            - containerPort: 19120
---
apiVersion: v1
kind: Service
metadata:
  name: nessie
spec:
  type: NodePort
  ports:
    - name: nessie-api
      port: 19120
      targetPort: 19120
      nodePort: 31920
  selector:
    app: nessie
